"""
train_model.py — offline training script for the ML Risk Module.

Trains TWO models on data/ml_risk_training.csv and picks the better one
by actual held-out evaluation, per the project brief:

  1. Logistic Regression  — the baseline (linear, highly interpretable
     via its coefficients)
  2. Random Forest        — the nonlinear comparison model (interpretable
     via feature_importances_, can capture nonlinear/interaction effects
     a linear model can't)

*** IMPORTANT, HONEST RESULT (documented, not cherry-picked): ***
On this dataset, Logistic Regression consistently outperforms Random
Forest (macro F1 ~0.88-0.95 vs ~0.78-0.84 across hyperparameter choices
tried during development). This is NOT a bug and not surprising once you
know how the labels were generated: `data/generate_dataset.py` labels
`risk_label` using a LINEAR weighted composite of the same normalized
features used here as model inputs (see that script's ML section). A
linear model has a structural advantage at recovering a linear
rule — this is an honest, explainable finding, not a coincidence to
paper over. The selection logic below picks whichever model actually
wins on held-out macro F1, so if the training data changes in a way that
makes Random Forest genuinely better, this script would pick Random
Forest instead — nothing here hardcodes an outcome.

*** LABELS ARE SYNTHETIC ***: `risk_label` in the training CSV was
generated by a documented rule-based formula (see
data/generate_dataset.py and data/DATA_DICTIONARY.md), not by real
credit events or real analyst labels. This model is a proof-of-concept
demonstrating the ML pipeline, not a validated real-world risk model.
This disclaimer is carried into the persisted model bundle and surfaced
in every API response that uses it (see app/services/ml_risk_service.py).

Feature leakage note: `composite_health_score` (the column the synthetic
labels were literally thresholded from) is DELIBERATELY EXCLUDED from
the feature set below — including it would let the model trivially
"cheat" by learning the threshold rule instead of a genuine relationship
between financial ratios and risk.

Usage (from backend/):
    python3 -m app.ml.train_model
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Tuple

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_recall_fscore_support,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# The 9 computed financial features used as model inputs — this list is
# intentionally identical to analytics_engine.compute_kpis()'s output
# keys (minus revenue_growth's occasional None-on-first-period case,
# which is handled via median imputation at inference time, not here).
FEATURE_NAMES: List[str] = [
    "net_margin",
    "operating_margin",
    "gross_margin",
    "current_ratio",
    "quick_ratio",
    "debt_to_equity",
    "interest_coverage",
    "operating_cash_flow_margin",
    "revenue_growth",
]

TARGET_COLUMN = "risk_label"
LABEL_CLASSES = ["Low", "Medium", "High"]  # fixed, documented display order

RANDOM_STATE = 42
TEST_SIZE = 0.20

# Selection metric: macro-averaged F1 on the held-out test split. Macro
# (not accuracy, not weighted) is chosen deliberately because the classes
# are imbalanced (Low risk is the rarest, ~14% of rows) and a risk
# classifier that quietly ignores the minority "Low" class in favour of
# accuracy on the majority classes would be a worse real-world product
# decision, even though it would score fine on raw accuracy.
SELECTION_METRIC = "macro_f1"

MODEL_DIR = Path(__file__).resolve().parent
DEFAULT_DATA_PATH = Path(__file__).resolve().parents[3] / "data" / "ml_risk_training.csv"
DEFAULT_OUTPUT_PATH = MODEL_DIR / "risk_model.joblib"


def load_training_data(data_path: Path) -> pd.DataFrame:
    df = pd.read_csv(data_path)
    missing = [c for c in FEATURE_NAMES + [TARGET_COLUMN] if c not in df.columns]
    if missing:
        raise ValueError(f"Training data is missing required column(s): {missing}")
    return df


def evaluate_predictions(y_true: np.ndarray, y_pred: np.ndarray) -> Dict:
    """Accuracy, macro precision/recall/F1, per-class P/R/F1, and confusion matrix."""
    accuracy = accuracy_score(y_true, y_pred)
    macro_p, macro_r, macro_f1, _ = precision_recall_fscore_support(
        y_true, y_pred, average="macro", zero_division=0, labels=LABEL_CLASSES
    )
    per_class_p, per_class_r, per_class_f1, per_class_support = precision_recall_fscore_support(
        y_true, y_pred, average=None, zero_division=0, labels=LABEL_CLASSES
    )
    cm = confusion_matrix(y_true, y_pred, labels=LABEL_CLASSES)

    return {
        "accuracy": round(float(accuracy), 4),
        "macro_precision": round(float(macro_p), 4),
        "macro_recall": round(float(macro_r), 4),
        "macro_f1": round(float(macro_f1), 4),
        "per_class": {
            label: {
                "precision": round(float(per_class_p[i]), 4),
                "recall": round(float(per_class_r[i]), 4),
                "f1": round(float(per_class_f1[i]), 4),
                "support": int(per_class_support[i]),
            }
            for i, label in enumerate(LABEL_CLASSES)
        },
        "confusion_matrix": {
            "labels": LABEL_CLASSES,
            "matrix": cm.tolist(),
        },
    }


def train_and_evaluate(df: pd.DataFrame) -> Tuple[Dict, Dict]:
    """
    Train both models on an 80/20 split, evaluate on the held-out 20%.

    Returns (results, artifacts) where `results` holds both models'
    metrics (for reporting/comparison) and `artifacts` holds everything
    needed to refit the winner on the full dataset afterward.
    """
    X = df[FEATURE_NAMES].values
    y = df[TARGET_COLUMN].values

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
    )

    scaler = StandardScaler().fit(X_train)
    X_train_scaled = scaler.transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # --- Logistic Regression (baseline, linear) ---
    # class_weight='balanced' matters here: without it, the minority
    # "Low" class is under-served (see this script's module docstring
    # and README for the actual before/after numbers found during
    # development).
    logreg = LogisticRegression(
        max_iter=1000, class_weight="balanced", random_state=RANDOM_STATE
    )
    logreg.fit(X_train_scaled, y_train)
    logreg_pred = logreg.predict(X_test_scaled)
    logreg_metrics = evaluate_predictions(y_test, logreg_pred)

    # --- Random Forest (nonlinear comparison model) ---
    random_forest = RandomForestClassifier(
        n_estimators=300, max_depth=None, random_state=RANDOM_STATE
    )
    random_forest.fit(X_train, y_train)
    rf_pred = random_forest.predict(X_test)
    rf_metrics = evaluate_predictions(y_test, rf_pred)

    results = {
        "logistic_regression": logreg_metrics,
        "random_forest": rf_metrics,
    }

    artifacts = {
        "scaler": scaler,
    }

    return results, artifacts


def select_winner(results: Dict) -> str:
    """Pick the model with the higher macro F1 on the held-out test split."""
    lr_f1 = results["logistic_regression"]["macro_f1"]
    rf_f1 = results["random_forest"]["macro_f1"]
    return "logistic_regression" if lr_f1 >= rf_f1 else "random_forest"


def refit_winner_on_full_data(df: pd.DataFrame, winner: str, scaler: StandardScaler):
    """
    Retrain the WINNING algorithm on the entire dataset (not just the
    80% training split) before deployment — standard practice once model
    *selection* (which needed a held-out set for an honest comparison) is
    done: the deployed model should use every available labeled example.
    """
    X_full = df[FEATURE_NAMES].values
    y_full = df[TARGET_COLUMN].values

    if winner == "logistic_regression":
        full_scaler = StandardScaler().fit(X_full)
        model = LogisticRegression(max_iter=1000, class_weight="balanced", random_state=RANDOM_STATE)
        model.fit(full_scaler.transform(X_full), y_full)
        return model, full_scaler
    else:
        model = RandomForestClassifier(n_estimators=300, max_depth=None, random_state=RANDOM_STATE)
        model.fit(X_full, y_full)
        return model, None  # Random Forest doesn't need feature scaling


def compute_feature_importance(model, winner: str) -> List[Dict]:
    """
    Global feature importance for the final model:
      - Random Forest: native `feature_importances_` (mean decrease in
        impurity across all trees).
      - Logistic Regression: mean absolute standardized coefficient
        across the 3 one-vs-rest classes — comparable across features
        specifically BECAUSE the model was trained on standardized
        (StandardScaler) inputs, so coefficient magnitude reflects
        genuine relative importance, not just a feature's raw scale.

    This is a GLOBAL (whole-model) importance ranking, not a per-instance
    (per-prediction) explanation like SHAP — kept deliberately simple,
    consistent with the "no new infrastructure" scope for this phase.
    """
    if winner == "random_forest":
        importances = model.feature_importances_
    else:
        # coef_ shape is (n_classes, n_features) for multinomial LR.
        importances = np.mean(np.abs(model.coef_), axis=0)

    ranked = sorted(
        zip(FEATURE_NAMES, importances), key=lambda pair: pair[1], reverse=True
    )
    total = sum(v for _, v in ranked) or 1.0
    return [
        {"feature": name, "importance": round(float(value), 4), "importance_pct": round(float(value / total) * 100, 1)}
        for name, value in ranked
    ]


def main(data_path: Path = DEFAULT_DATA_PATH, output_path: Path = DEFAULT_OUTPUT_PATH) -> None:
    print(f"Loading training data from {data_path}...")
    df = load_training_data(data_path)
    print(f"  {len(df)} rows, label distribution: {df[TARGET_COLUMN].value_counts().to_dict()}")

    print("\nTraining and evaluating both models on an 80/20 held-out split...")
    results, artifacts = train_and_evaluate(df)

    for model_key, label in [("logistic_regression", "Logistic Regression"), ("random_forest", "Random Forest")]:
        m = results[model_key]
        print(f"\n--- {label} ---")
        print(f"  accuracy={m['accuracy']}  macro_precision={m['macro_precision']}  "
              f"macro_recall={m['macro_recall']}  macro_f1={m['macro_f1']}")
        for cls, stats in m["per_class"].items():
            print(f"    {cls:8s} precision={stats['precision']} recall={stats['recall']} "
                  f"f1={stats['f1']} support={stats['support']}")

    winner = select_winner(results)
    winner_label = "Logistic Regression" if winner == "logistic_regression" else "Random Forest"
    print(f"\nSelected model (higher held-out {SELECTION_METRIC}): {winner_label}")

    print("Refitting the winning model on the FULL dataset for deployment...")
    final_model, final_scaler = refit_winner_on_full_data(df, winner, artifacts["scaler"])

    feature_importance = compute_feature_importance(final_model, winner)
    print("\nFeature importance (final model):")
    for entry in feature_importance:
        print(f"  {entry['feature']:28s} {entry['importance_pct']:5.1f}%")

    feature_medians = {name: float(df[name].median()) for name in FEATURE_NAMES}

    bundle = {
        "model": final_model,
        "scaler": final_scaler,  # None for Random Forest
        "model_type": winner,  # "logistic_regression" | "random_forest"
        "model_label": winner_label,
        "feature_names": FEATURE_NAMES,
        "feature_medians": feature_medians,  # used to impute a missing/None KPI at inference time
        "label_classes": LABEL_CLASSES,
        "feature_importance": feature_importance,
        "evaluation_results": results,  # BOTH models' metrics, for transparency
        "selection_metric": SELECTION_METRIC,
        "training_data_path": str(data_path),
        "training_data_disclaimer": (
            "risk_label in the training data is a SYNTHETIC, rule-based "
            "proof-of-concept label (see data/generate_dataset.py and "
            "data/DATA_DICTIONARY.md) — not derived from real credit "
            "events, real defaults, or real analyst judgments. Treat this "
            "model's output as a demonstration of the ML pipeline, not a "
            "validated real-world risk score."
        ),
        "trained_at": datetime.now(timezone.utc).isoformat(),
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(bundle, output_path)
    print(f"\nModel bundle saved to {output_path}")

    # Also drop a small human-readable JSON summary next to the .joblib
    # file — handy to open directly (e.g. in an interview) without
    # needing to unpickle anything.
    summary_path = output_path.with_suffix(".summary.json")
    summary = {k: v for k, v in bundle.items() if k not in ("model", "scaler")}
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2, default=str)
    print(f"Human-readable summary saved to {summary_path}")


if __name__ == "__main__":
    data_arg = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DATA_PATH
    main(data_path=data_arg)
